module.exports = {
  KEYBOARD_TOGGLE: 'KEYBOARD_TOGGLE',
  MOUSE_TOGGLE: 'MOUSE_TOGGLE',

  KEY_PRESS: 'KEY_PRESS',
  KEY_TOGGLE: 'KEY_TOGGLE',
  MOUSE_CLICK: 'MOUSE_CLICK',
  MOUSE_MOVE: 'MOUSE_MOVE',
}
